name: CI

on:
  pull_request:
    branches:
      - main # branch to monitor

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # node version

      - name: Install dependencies
        run: yarn install

      - name: Running Backend Jest Test
        run: cd backend && yarn install && yarn test
